// input-files/vue/renderer/Link.vue
<template>
  <a :class="{ active: pageContext.urlPathname === $attrs.href }">
    <slot />
  </a>
</template>
<style scoped>
a {
  padding: 3px 10px;
}
a.active {
  background-color: #eee;
}
</style>
<script lang="ts" setup>
import { usePageContext } from "./usePageContext";
const pageContext = usePageContext();
</script>

// original-boilerplates/js-react/renderer/Link.jsx
import React from "react";
import { usePageContext } from "./usePageContext";

export { Link };

function Link(props) {
  const pageContext = usePageContext();
  const className = [
    props.className,
    pageContext.urlPathname === props.href && "is-active",
  ]
    .filter(Boolean)
    .join(" ");
  return <a {...props} className={className} />;
}
